BEGIN TRANSACTION;
INSERT INTO "events" VALUES('hesse-darmstadt+founded',1740,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.ludwig-ix+birth',1719,12,15,'Darmstadt, Landgraviate of Hesse-Darmstadt',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.ludwig-ix+death',1790,4,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.ludwig-ix+hesse-darmstadt.landgrave+start',1768,10,12,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.friederike-luise+birth',1751,10,16,'Prenzlau, Electorate of Brandenburg',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.friederike-luise+death',1805,2,25,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.ludwig-i+birth',1753,6,14,'Prenzlau, Margraviate of Brandenburg',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.ludwig-i+death',1830,4,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.ludwig-i+hesse-and-by-rhine.grand-duke+start',1806,8,14,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.ludwig-i+hesse-darmstadt.landgrave+start',1790,4,6,NULL,NULL,NULL,NULL,'Ludwig X',NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.landgrave+abolished',1806,8,14,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.ludwig-ix+hesse-darmstadt.friederike-luise+family+married',1741,8,12,'Zweibrücken, Duchy of Palatinate-Zweibrücken',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.elizabeth-ii+birth',1926,4,21,'Mayfair, London, England',NULL,'York','of','Elizabeth',NULL,NULL);
INSERT INTO "events" VALUES('windsor.elizabeth-ii+death',2022,9,8,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.elizabeth-ii+united-kingdom.queen+start',1952,2,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('mountbatten.philip+birth',1921,6,10,'Mon Repos, Corfu, Greece',NULL,'Glücksburg','of','Philip',NULL,NULL);
INSERT INTO "events" VALUES('mountbatten.philip+death',2021,4,9,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('mountbatten.philip+edinburgh.duke+start',1947,11,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('mountbatten.philip+windsor.elizabeth-ii+family+married',1947,11,20,'Westminster Abbey, London, England',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.charles-iii+birth',1948,11,14,'Buckingham Palace, London, England',NULL,'Edinburgh','of','Charles',NULL,NULL);
INSERT INTO "events" VALUES('windsor.charles-iii+united-kingdom.king+start',2022,9,8,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('battenberg.alice+birth',1885,2,25,'Windsor Castle, Berkshire, England',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('battenberg.alice+death',1969,12,5,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('glucksburg.andrew+birth',1882,2,2,'Tatoi Palace, Athens, Greece',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('glucksburg.andrew+death',1944,12,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('glucksburg.andrew+battenberg.alice+family+married',1903,10,6,'Darmstadt, Grand Duchy of Hesse and by Rhine',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('battenberg.louis+birth',1854,5,24,'Graz, Austrian Empire',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('battenberg.louis+death',1921,9,11,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.victoria+birth',1863,4,5,'Windsor Castle, Berkshire, England',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.victoria+death',1950,9,24,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('battenberg.louis+hesse-darmstadt.victoria+family+married',1884,4,30,'Darmstadt, Grand Duchy of Hesse and by Rhine',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('milford-haven.marquess+created',1917,7,17,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('battenberg.louis+milford-haven.marquess+start',1917,7,17,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.charles-iii+wales.prince+start',1958,7,26,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.charles-iii+wales.prince+end',2022,9,8,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.charles-iii+edinburgh.duke+start',2021,4,9,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.charles-iii+edinburgh.duke+end',2022,9,8,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.alexander+birth',1823,7,15,'Darmstadt, Grand Duchy of Hesse and by Rhine',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.alexander+death',1888,12,15,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('battenberg.julia+birth',1825,11,24,'Warsaw, Congress Poland',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('battenberg.julia+death',1895,9,19,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.alexander+battenberg.julia+family+married',1851,10,28,'Breslau, Province of Silesia, Prussia',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.louise+birth',1761,2,15,'Darmstadt, Landgraviate of Hesse-Darmstadt',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.louise+death',1829,10,24,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.ludwig-i+hesse-darmstadt.louise+family+married',1777,2,19,'Darmstadt, Landgraviate of Hesse-Darmstadt',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.ludwig-ii+birth',1777,12,26,'Darmstadt, Landgraviate of Hesse-Darmstadt',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.ludwig-ii+death',1848,6,16,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.ludwig-ii+hesse-and-by-rhine.grand-duke+start',1830,4,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('baden.wilhelmine+birth',1788,9,21,'Karlsruhe, Margraviate of Baden',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('baden.wilhelmine+death',1836,1,27,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.ludwig-ii+baden.wilhelmine+family+married',1804,6,19,'Karlsruhe, Electorate of Baden',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hanover.victoria+death',1901,1,22,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hanover.victoria+birth',1819,5,24,'Kensington Palace, London, England','Victoria','Kent','of',NULL,NULL,NULL);
INSERT INTO "events" VALUES('saxe-coburg-gotha.albert+death',1861,12,14,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('saxe-coburg-gotha.albert+birth',1819,8,26,'The Rosenau, Duchy of Saxe-Coburg-Saalfeld',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('saxe-coburg-gotha.albert+hanover.victoria+family+married',1840,2,10,'St James''s Place, London, England',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hanover.victoria+united-kingdom.queen+start',1837,6,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('saxe-coburg-gotha.edward-vii+death',1910,5,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('saxe-coburg-gotha.edward-vii+birth',1841,11,9,'Buckingham Palace, London, England',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('saxe-coburg-gotha.edward-vii+united-kingdom.king+start',1901,1,22,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('saxe-coburg-gotha.edward-vii+wales.prince+start',1841,12,8,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('saxe-coburg-gotha.edward-vii+wales.prince+end',1901,1,22,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('glucksburg.alexandra+death',1925,11,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('glucksburg.alexandra+birth',1844,12,1,'Yellow Palace, Copenhagen, Denmark',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('saxe-coburg-gotha.edward-vii+glucksburg.alexandra+family+married',1863,3,10,'St George''s Chapel, Windsor Castle, Berkshire, England',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.george-v+birth',1865,6,3,'Marlborough House, London, England','George','Wales','of',NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.george-v+death',1936,1,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.george-v+united-kingdom.king+start',1910,5,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.george-v+wales.prince+start',1901,11,9,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.george-v+wales.prince+end',1910,5,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('teck.mary+death',1953,3,24,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('teck.mary+birth',1867,5,26,'Kensington Palace, London, England',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.george-v+teck.mary+family+married',1893,7,6,'St James''s Palace, London, England',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.george-vi+death',1952,2,15,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.george-vi+birth',1895,12,14,'Sandringham, Norfolk, England','Albert','York','of',NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.george-vi+united-kingdom.king+start',1936,12,11,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.george-vi+york.duke+start',1920,6,4,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.george-vi+york.duke+end',1936,12,11,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('bowes-lyon.elizabeth+death',2002,3,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('bowes-lyon.elizabeth+birth',1900,8,4,'London, England',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.george-vi+bowes-lyon.elizabeth+family+married',1923,4,26,'Westminster Abbey, London, England',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.edward-viii+death',1972,5,28,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.edward-viii+birth',1894,6,23,'White Lodge, Surrey, England','Edward','York','of',NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.edward-viii+united-kingdom.king+start',1936,1,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.edward-viii+united-kingdom.king+end',1936,12,11,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.edward-viii+windsor.duke+start',1936,12,12,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.edward-viii+wales.prince+start',1910,6,23,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.edward-viii+wales.prince+end',1936,1,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.george-v+york.duke+start',1892,5,24,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.george-v+york.duke+end',1910,5,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('saxe-coburg-gotha.alice+death',1878,12,14,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('saxe-coburg-gotha.alice+birth',1843,4,25,'Buckingham Palace, London, England',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.ludwig-iv+death',1892,3,13,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.ludwig-iv+birth',1837,9,12,'Prinz-Carl-Palais, Darmstadt, Grand Duchy of Hesse',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.ludwig-iv+saxe-coburg-gotha.alice+family+married',1862,7,1,'Osborne House, Isle of Wight, England',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.ludwig-iv+hesse-and-by-rhine.grand-duke+start',1877,6,13,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.karl+death',1877,3,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.karl+birth',1809,4,23,'Darmstadt, Grand Duchy of Hesse and by Rhine',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hohenzollern.elisabeth+death',1885,3,21,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hohenzollern.elisabeth+birth',1815,6,18,'Berlin Palace, Kingdom of Prussia',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.karl+hohenzollern.elisabeth+family+married',1836,10,22,'Berlin, Kingdom of Prussia',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('battenberg+founded',1851,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('glucksburg.christian-ix+death',1906,1,29,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('glucksburg.christian-ix+birth',1818,4,8,'Gottorf Castle, Duchy of Schleswig',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-kassel.louise+death',1898,9,29,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-kassel.louise+birth',1817,9,7,'Kassel, Electorate of Hesse',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('glucksburg.christian-ix+hesse-kassel.louise+family+married',1842,5,26,'Amalienborg, Copenhagen, Denmark',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('schleswig-holstein.duke+abolished',1864,10,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('saxe-lauenburg.duke+abolished',1864,10,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('glucksburg.christian-ix+schleswig-holstein.duke+start',1863,11,15,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('glucksburg.christian-ix+saxe-lauenburg.duke+start',1863,11,15,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('glucksburg.christian-ix+denmark.king+start',1863,11,15,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('glucksburg.george-i+death',1913,3,18,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('glucksburg.george-i+birth',1845,12,24,'Yellow Palace, Copenhagen, Denmark','William','Schleswig-Holstein-Sonderburg-Glücksburg','of',NULL,NULL,NULL);
INSERT INTO "events" VALUES('romanov.olga-constantinovna+death',1926,6,18,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('romanov.olga-constantinovna+birth',1851,9,3,'Pavlovsk Palace, Saint Petersburg, Russia',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('glucksburg.george-i+romanov.olga-constantinovna+family+married',1867,10,27,'Winter Palace, Saint Petersburg, Russia',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('glucksburg.george-i+greece.king+start',1863,3,30,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "houses" VALUES('hesse','Hesse',NULL,NULL,NULL,NULL);
INSERT INTO "houses" VALUES('hesse-darmstadt','Hesse-Darmstadt','hesse',NULL,'hesse-darmstadt.ludwig-ix','hesse-darmstadt+founded');
INSERT INTO "houses" VALUES('windsor','Windsor',NULL,'saxe-coburg-gotha',NULL,NULL);
INSERT INTO "houses" VALUES('glucksburg','Glücksburg',NULL,'beck',NULL,NULL);
INSERT INTO "houses" VALUES('mountbatten','Mountbatten',NULL,'battenberg',NULL,NULL);
INSERT INTO "houses" VALUES('battenberg','Battenberg','hesse-darmstadt',NULL,'battenberg.julia','battenberg+founded');
INSERT INTO "houses" VALUES('zahringen','Zähringen',NULL,NULL,NULL,NULL);
INSERT INTO "houses" VALUES('baden','Baden','zahringen',NULL,NULL,NULL);
INSERT INTO "houses" VALUES('hanover','Hanover',NULL,NULL,NULL,NULL);
INSERT INTO "houses" VALUES('saxe-coburg-saalfeld','Saxe-Coburg-Saalfeld',NULL,NULL,NULL,NULL);
INSERT INTO "houses" VALUES('saxe-coburg-gotha','Saxe-Coburg and Gotha',NULL,'saxe-coburg-saalfeld',NULL,NULL);
INSERT INTO "houses" VALUES('wurttemberg','Württemberg',NULL,NULL,NULL,NULL);
INSERT INTO "houses" VALUES('teck','Teck','wurttemberg',NULL,NULL,NULL);
INSERT INTO "houses" VALUES('hohenzollern','Hohenzollern',NULL,NULL,NULL,NULL);
INSERT INTO "houses" VALUES('beck','Beck','oldenburg',NULL,NULL,NULL);
INSERT INTO "houses" VALUES('hesse-kassel','Hesse-Kassel','hesse',NULL,NULL,NULL);
INSERT INTO "houses" VALUES('romanov','Romanov','holstein-gottorp',NULL,NULL,NULL);
INSERT INTO "houses" VALUES('holstein-gottorp','Holstein-Gottorp','oldenburg',NULL,NULL,NULL);
INSERT INTO "houses" VALUES('oldenburg','Oldenburg',NULL,NULL,NULL,NULL);
INSERT INTO "titles" VALUES('hesse-darmstadt.landgrave','Landgrave of Hesse-Darmstadt',NULL,NULL,'hesse-darmstadt.landgrave+abolished');
INSERT INTO "titles" VALUES('hesse-and-by-rhine.grand-duke','Grand Duke of Hesse and by Rhine',NULL,NULL,NULL);
INSERT INTO "titles" VALUES('united-kingdom.king','King of the United Kingdom','Monarch of the United Kingdom',NULL,NULL);
INSERT INTO "titles" VALUES('united-kingdom.queen','Queen of the United Kingdom','Monarch of the United Kingdom',NULL,NULL);
INSERT INTO "titles" VALUES('edinburgh.duke','Duke of Edinburgh',NULL,NULL,NULL);
INSERT INTO "titles" VALUES('milford-haven.marquess','Marquess of Milford Haven',NULL,'milford-haven.marquess+created',NULL);
INSERT INTO "titles" VALUES('wales.prince','Prince of Wales',NULL,NULL,NULL);
INSERT INTO "titles" VALUES('york.duke','Duke of York',NULL,NULL,NULL);
INSERT INTO "titles" VALUES('windsor.duke','Duke of Windsor',NULL,NULL,NULL);
INSERT INTO "titles" VALUES('denmark.king','King of Denmark',NULL,NULL,NULL);
INSERT INTO "titles" VALUES('schleswig-holstein.duke','Duke of Schleswig-Holstein',NULL,NULL,'schleswig-holstein.duke+abolished');
INSERT INTO "titles" VALUES('saxe-lauenburg.duke','Duke of Saxe-Lauenburg',NULL,NULL,'saxe-lauenburg.duke+abolished');
INSERT INTO "titles" VALUES('greece.king','King of the Hellenes',NULL,NULL,NULL);
INSERT INTO "people" VALUES('hesse-darmstadt.ludwig-ix','Ludwig',NULL,NULL,'Ludwig IX',NULL,NULL,'hesse-darmstadt.ludwig-ix+birth','hesse-darmstadt.ludwig-ix+death','hesse-darmstadt',NULL,'male');
INSERT INTO "people" VALUES('hesse-darmstadt.friederike-luise','Friederike Luise','Hesse-Darmstadt','of',NULL,NULL,NULL,'hesse-darmstadt.friederike-luise+birth','hesse-darmstadt.friederike-luise+death','hesse-darmstadt',NULL,'female');
INSERT INTO "people" VALUES('hesse-darmstadt.ludwig-i','Ludwig',NULL,NULL,'Ludwig I',NULL,NULL,'hesse-darmstadt.ludwig-i+birth','hesse-darmstadt.ludwig-i+death','hesse-darmstadt',NULL,'male');
INSERT INTO "people" VALUES('windsor.elizabeth-ii','Elizabeth Alexandra Mary',NULL,NULL,'Elizabeth II',NULL,NULL,'windsor.elizabeth-ii+birth','windsor.elizabeth-ii+death','windsor',NULL,'female');
INSERT INTO "people" VALUES('mountbatten.philip','Philip','Mountbatten',NULL,NULL,NULL,NULL,'mountbatten.philip+birth','mountbatten.philip+death','mountbatten','glucksburg','male');
INSERT INTO "people" VALUES('windsor.charles-iii','Charles Philip Arthur George',NULL,NULL,'Charles III',NULL,NULL,'windsor.charles-iii+birth',NULL,'windsor',NULL,'male');
INSERT INTO "people" VALUES('battenberg.alice','Victoria Alice Elizabeth Julia Marie','Battenberg','of','Alice',NULL,NULL,'battenberg.alice+birth','battenberg.alice+death','battenberg',NULL,'female');
INSERT INTO "people" VALUES('glucksburg.andrew','Andrew','Glücksburg','of',NULL,NULL,NULL,'glucksburg.andrew+birth','glucksburg.andrew+death','glucksburg',NULL,'male');
INSERT INTO "people" VALUES('battenberg.louis','Louis Alexander','Battenberg','of',NULL,NULL,NULL,'battenberg.louis+birth','battenberg.louis+death','mountbatten','battenberg','male');
INSERT INTO "people" VALUES('hesse-darmstadt.victoria','Victoria Alberta Elisabeth Mathilde Marie','Hesse and by Rhine','of',NULL,NULL,NULL,'hesse-darmstadt.victoria+birth','hesse-darmstadt.victoria+death','hesse-darmstadt',NULL,'female');
INSERT INTO "people" VALUES('hesse-darmstadt.alexander','Alexander Ludwig Georg Friedrich Emil','Hesse and by Rhine','of',NULL,NULL,NULL,'hesse-darmstadt.alexander+birth','hesse-darmstadt.alexander+death','hesse-darmstadt',NULL,'male');
INSERT INTO "people" VALUES('battenberg.julia','Julia Therese Salomea','Hauke','von',NULL,NULL,NULL,'battenberg.julia+birth','battenberg.julia+death','battenberg',NULL,'female');
INSERT INTO "people" VALUES('hesse-darmstadt.louise','Louise Henriette Karoline','Hesse-Darmstadt','of',NULL,NULL,NULL,'hesse-darmstadt.louise+birth','hesse-darmstadt.louise+death','hesse-darmstadt',NULL,'female');
INSERT INTO "people" VALUES('hesse-darmstadt.ludwig-ii','Ludwig',NULL,NULL,'Ludwig II',NULL,NULL,'hesse-darmstadt.ludwig-ii+birth','hesse-darmstadt.ludwig-ii+death','hesse-darmstadt',NULL,'male');
INSERT INTO "people" VALUES('baden.wilhelmine','Wilhelmine Louise','Baden','of',NULL,NULL,NULL,'baden.wilhelmine+birth','baden.wilhelmine+death','baden',NULL,'female');
INSERT INTO "people" VALUES('hanover.victoria','Alexandrina Victoria',NULL,NULL,'Victoria',NULL,NULL,'hanover.victoria+birth','hanover.victoria+death','hanover',NULL,'female');
INSERT INTO "people" VALUES('saxe-coburg-gotha.albert','Franz August Karl Albert Emanuel','Saxe-Coburg and Gotha','of','Albert',NULL,NULL,'saxe-coburg-gotha.albert+birth','saxe-coburg-gotha.albert+death','saxe-coburg-gotha','saxe-coburg-saalfeld','male');
INSERT INTO "people" VALUES('saxe-coburg-gotha.edward-vii','Albert Edward',NULL,NULL,'Edward VII',NULL,NULL,'saxe-coburg-gotha.edward-vii+birth','saxe-coburg-gotha.edward-vii+death','saxe-coburg-gotha',NULL,'male');
INSERT INTO "people" VALUES('glucksburg.alexandra','Alexandra Caroline Marie Charlotte Louise Julia','Glücksburg','of',NULL,NULL,NULL,'glucksburg.alexandra+birth','glucksburg.alexandra+death','glucksburg',NULL,'female');
INSERT INTO "people" VALUES('windsor.george-v','George Frederick Ernest Albert',NULL,NULL,'George V',NULL,NULL,'windsor.george-v+birth','windsor.george-v+death','windsor','saxe-coburg-gotha','male');
INSERT INTO "people" VALUES('teck.mary','Victoria Mary Augusta Louise Olga Pauline Claudine Agnes','Teck','of','Mary',NULL,NULL,'teck.mary+birth','teck.mary+death','teck',NULL,'female');
INSERT INTO "people" VALUES('windsor.george-vi','Albert Frederick Arthur George',NULL,NULL,'George VI',NULL,NULL,'windsor.george-vi+birth','windsor.george-vi+death','windsor','saxe-coburg-gotha','male');
INSERT INTO "people" VALUES('bowes-lyon.elizabeth','Elizabeth Angela Marguerite','Bowes-Lyon',NULL,NULL,NULL,NULL,'bowes-lyon.elizabeth+birth','bowes-lyon.elizabeth+death',NULL,NULL,'female');
INSERT INTO "people" VALUES('windsor.edward-viii','Edward Albert Christian George Andrew Patrick David',NULL,NULL,'Edward VIII',NULL,NULL,'windsor.edward-viii+birth','windsor.edward-viii+death','windsor','saxe-coburg-gotha','male');
INSERT INTO "people" VALUES('saxe-coburg-gotha.alice','Alice Maud Mary','Saxe-Coburg and Gotha','of',NULL,NULL,NULL,'saxe-coburg-gotha.alice+birth','saxe-coburg-gotha.alice+death','saxe-coburg-gotha',NULL,'female');
INSERT INTO "people" VALUES('hesse-darmstadt.ludwig-iv','Friedrich Wilhelm Ludwig Karl',NULL,NULL,'Ludwig IV',NULL,NULL,'hesse-darmstadt.ludwig-iv+birth','hesse-darmstadt.ludwig-iv+death','hesse-darmstadt',NULL,'male');
INSERT INTO "people" VALUES('hesse-darmstadt.karl','Karl Wilhelm Ludewig','Hesse and by Rhine','of',NULL,NULL,NULL,'hesse-darmstadt.karl+birth','hesse-darmstadt.karl+death','hesse-darmstadt',NULL,'male');
INSERT INTO "people" VALUES('hohenzollern.elisabeth','Marie Elisabeth Karoline Viktoria','Hohenzollern','of',NULL,NULL,NULL,'hohenzollern.elisabeth+birth','hohenzollern.elisabeth+death','hohenzollern',NULL,'female');
INSERT INTO "people" VALUES('glucksburg.christian-ix','Christian',NULL,NULL,'Christian IX',NULL,NULL,'glucksburg.christian-ix+birth','glucksburg.christian-ix+death','glucksburg','beck','male');
INSERT INTO "people" VALUES('hesse-kassel.louise','Luise Wilhelmine Friederike Caroline Auguste Julie','Hesse-Kassel','of',NULL,NULL,NULL,'hesse-kassel.louise+birth','hesse-kassel.louise+death','hesse-kassel',NULL,'female');
INSERT INTO "people" VALUES('glucksburg.george-i','Christian William Ferdinand Adolph George',NULL,NULL,'George I',NULL,NULL,'glucksburg.george-i+birth','glucksburg.george-i+death','glucksburg',NULL,'male');
INSERT INTO "people" VALUES('romanov.olga-constantinovna','Olga Constantinovna','Romanov',NULL,'Olga Constantinovna',NULL,NULL,'romanov.olga-constantinovna+birth','romanov.olga-constantinovna+death','romanov',NULL,'female');
INSERT INTO "tenures" VALUES(1,'hesse-darmstadt.ludwig-ix','hesse-darmstadt.landgrave','hesse-darmstadt.ludwig-ix+hesse-darmstadt.landgrave+start',NULL,NULL,0,NULL);
INSERT INTO "tenures" VALUES(2,'hesse-darmstadt.ludwig-i','hesse-and-by-rhine.grand-duke','hesse-darmstadt.ludwig-i+hesse-and-by-rhine.grand-duke+start',NULL,NULL,0,NULL);
INSERT INTO "tenures" VALUES(3,'hesse-darmstadt.ludwig-i','hesse-darmstadt.landgrave','hesse-darmstadt.ludwig-i+hesse-darmstadt.landgrave+start',NULL,NULL,0,NULL);
INSERT INTO "tenures" VALUES(4,'windsor.elizabeth-ii','united-kingdom.queen','windsor.elizabeth-ii+united-kingdom.queen+start',NULL,NULL,0,NULL);
INSERT INTO "tenures" VALUES(5,'mountbatten.philip','edinburgh.duke','mountbatten.philip+edinburgh.duke+start',NULL,NULL,0,NULL);
INSERT INTO "tenures" VALUES(6,'windsor.charles-iii','united-kingdom.king','windsor.charles-iii+united-kingdom.king+start',NULL,NULL,0,NULL);
INSERT INTO "tenures" VALUES(7,'battenberg.louis','milford-haven.marquess','battenberg.louis+milford-haven.marquess+start',NULL,NULL,0,NULL);
INSERT INTO "tenures" VALUES(8,'windsor.charles-iii','wales.prince','windsor.charles-iii+wales.prince+start','windsor.charles-iii+wales.prince+end',NULL,0,NULL);
INSERT INTO "tenures" VALUES(9,'windsor.charles-iii','edinburgh.duke','windsor.charles-iii+edinburgh.duke+start','windsor.charles-iii+edinburgh.duke+end',NULL,0,NULL);
INSERT INTO "tenures" VALUES(10,'hesse-darmstadt.ludwig-ii','hesse-and-by-rhine.grand-duke','hesse-darmstadt.ludwig-ii+hesse-and-by-rhine.grand-duke+start',NULL,NULL,0,NULL);
INSERT INTO "tenures" VALUES(11,'hanover.victoria','united-kingdom.queen','hanover.victoria+united-kingdom.queen+start',NULL,NULL,0,NULL);
INSERT INTO "tenures" VALUES(12,'saxe-coburg-gotha.edward-vii','united-kingdom.king','saxe-coburg-gotha.edward-vii+united-kingdom.king+start',NULL,NULL,0,NULL);
INSERT INTO "tenures" VALUES(13,'saxe-coburg-gotha.edward-vii','wales.prince','saxe-coburg-gotha.edward-vii+wales.prince+start','saxe-coburg-gotha.edward-vii+wales.prince+end',NULL,0,NULL);
INSERT INTO "tenures" VALUES(14,'windsor.george-v','united-kingdom.king','windsor.george-v+united-kingdom.king+start',NULL,NULL,0,NULL);
INSERT INTO "tenures" VALUES(15,'windsor.george-v','wales.prince','windsor.george-v+wales.prince+start','windsor.george-v+wales.prince+end',NULL,0,NULL);
INSERT INTO "tenures" VALUES(16,'windsor.george-vi','united-kingdom.king','windsor.george-vi+united-kingdom.king+start',NULL,NULL,0,NULL);
INSERT INTO "tenures" VALUES(17,'windsor.george-vi','york.duke','windsor.george-vi+york.duke+start','windsor.george-vi+york.duke+end',NULL,0,NULL);
INSERT INTO "tenures" VALUES(18,'windsor.edward-viii','united-kingdom.king','windsor.edward-viii+united-kingdom.king+start','windsor.edward-viii+united-kingdom.king+end',NULL,0,NULL);
INSERT INTO "tenures" VALUES(19,'windsor.edward-viii','windsor.duke','windsor.edward-viii+windsor.duke+start',NULL,NULL,0,NULL);
INSERT INTO "tenures" VALUES(20,'windsor.edward-viii','wales.prince','windsor.edward-viii+wales.prince+start','windsor.edward-viii+wales.prince+end',NULL,0,NULL);
INSERT INTO "tenures" VALUES(21,'windsor.george-v','york.duke','windsor.george-v+york.duke+start','windsor.george-v+york.duke+end',NULL,0,NULL);
INSERT INTO "tenures" VALUES(22,'hesse-darmstadt.ludwig-iv','hesse-and-by-rhine.grand-duke','hesse-darmstadt.ludwig-iv+hesse-and-by-rhine.grand-duke+start',NULL,NULL,0,NULL);
INSERT INTO "tenures" VALUES(23,'glucksburg.christian-ix','denmark.king','glucksburg.christian-ix+denmark.king+start',NULL,NULL,0,NULL);
INSERT INTO "tenures" VALUES(24,'glucksburg.christian-ix','saxe-lauenburg.duke','glucksburg.christian-ix+saxe-lauenburg.duke+start',NULL,NULL,0,NULL);
INSERT INTO "tenures" VALUES(25,'glucksburg.christian-ix','schleswig-holstein.duke','glucksburg.christian-ix+schleswig-holstein.duke+start',NULL,NULL,0,NULL);
INSERT INTO "tenures" VALUES(26,'glucksburg.george-i','greece.king','glucksburg.george-i+greece.king+start',NULL,NULL,0,NULL);
INSERT INTO "families" VALUES('hesse-darmstadt.ludwig-ix+hesse-darmstadt.friederike-luise+family','hesse-darmstadt.ludwig-ix','hesse-darmstadt.friederike-luise','hesse-darmstadt.ludwig-ix+hesse-darmstadt.friederike-luise+family+married',NULL);
INSERT INTO "families" VALUES('mountbatten.philip+windsor.elizabeth-ii+family','mountbatten.philip','windsor.elizabeth-ii','mountbatten.philip+windsor.elizabeth-ii+family+married',NULL);
INSERT INTO "families" VALUES('glucksburg.andrew+battenberg.alice+family','glucksburg.andrew','battenberg.alice','glucksburg.andrew+battenberg.alice+family+married',NULL);
INSERT INTO "families" VALUES('battenberg.louis+hesse-darmstadt.victoria+family','battenberg.louis','hesse-darmstadt.victoria','battenberg.louis+hesse-darmstadt.victoria+family+married',NULL);
INSERT INTO "families" VALUES('hesse-darmstadt.alexander+battenberg.julia+family','hesse-darmstadt.alexander','battenberg.julia','hesse-darmstadt.alexander+battenberg.julia+family+married',NULL);
INSERT INTO "families" VALUES('hesse-darmstadt.ludwig-i+hesse-darmstadt.louise+family','hesse-darmstadt.ludwig-i','hesse-darmstadt.louise','hesse-darmstadt.ludwig-i+hesse-darmstadt.louise+family+married',NULL);
INSERT INTO "families" VALUES('hesse-darmstadt.ludwig-ii+baden.wilhelmine+family','hesse-darmstadt.ludwig-ii','baden.wilhelmine','hesse-darmstadt.ludwig-ii+baden.wilhelmine+family+married',NULL);
INSERT INTO "families" VALUES('saxe-coburg-gotha.albert+hanover.victoria+family','saxe-coburg-gotha.albert','hanover.victoria','saxe-coburg-gotha.albert+hanover.victoria+family+married',NULL);
INSERT INTO "families" VALUES('saxe-coburg-gotha.edward-vii+glucksburg.alexandra+family','saxe-coburg-gotha.edward-vii','glucksburg.alexandra','saxe-coburg-gotha.edward-vii+glucksburg.alexandra+family+married',NULL);
INSERT INTO "families" VALUES('windsor.george-v+teck.mary+family','windsor.george-v','teck.mary','windsor.george-v+teck.mary+family+married',NULL);
INSERT INTO "families" VALUES('windsor.george-vi+bowes-lyon.elizabeth+family','windsor.george-vi','bowes-lyon.elizabeth','windsor.george-vi+bowes-lyon.elizabeth+family+married',NULL);
INSERT INTO "families" VALUES('hesse-darmstadt.ludwig-iv+saxe-coburg-gotha.alice+family','hesse-darmstadt.ludwig-iv','saxe-coburg-gotha.alice','hesse-darmstadt.ludwig-iv+saxe-coburg-gotha.alice+family+married',NULL);
INSERT INTO "families" VALUES('hesse-darmstadt.karl+hohenzollern.elisabeth+family','hesse-darmstadt.karl','hohenzollern.elisabeth','hesse-darmstadt.karl+hohenzollern.elisabeth+family+married',NULL);
INSERT INTO "families" VALUES('glucksburg.christian-ix+hesse-kassel.louise+family','glucksburg.christian-ix','hesse-kassel.louise','glucksburg.christian-ix+hesse-kassel.louise+family+married',NULL);
INSERT INTO "families" VALUES('glucksburg.george-i+romanov.olga-constantinovna+family','glucksburg.george-i','romanov.olga-constantinovna','glucksburg.george-i+romanov.olga-constantinovna+family+married',NULL);
INSERT INTO "family_children" VALUES('hesse-darmstadt.ludwig-ix+hesse-darmstadt.friederike-luise+family','hesse-darmstadt.ludwig-i',0);
INSERT INTO "family_children" VALUES('mountbatten.philip+windsor.elizabeth-ii+family','windsor.charles-iii',0);
INSERT INTO "family_children" VALUES('glucksburg.andrew+battenberg.alice+family','mountbatten.philip',0);
INSERT INTO "family_children" VALUES('battenberg.louis+hesse-darmstadt.victoria+family','battenberg.alice',0);
INSERT INTO "family_children" VALUES('hesse-darmstadt.alexander+battenberg.julia+family','battenberg.louis',1);
INSERT INTO "family_children" VALUES('hesse-darmstadt.ludwig-i+hesse-darmstadt.louise+family','hesse-darmstadt.ludwig-ii',0);
INSERT INTO "family_children" VALUES('hesse-darmstadt.ludwig-ii+baden.wilhelmine+family','hesse-darmstadt.alexander',4);
INSERT INTO "family_children" VALUES('saxe-coburg-gotha.albert+hanover.victoria+family','saxe-coburg-gotha.edward-vii',1);
INSERT INTO "family_children" VALUES('saxe-coburg-gotha.edward-vii+glucksburg.alexandra+family','windsor.george-v',1);
INSERT INTO "family_children" VALUES('windsor.george-v+teck.mary+family','windsor.george-vi',1);
INSERT INTO "family_children" VALUES('windsor.george-vi+bowes-lyon.elizabeth+family','windsor.elizabeth-ii',0);
INSERT INTO "family_children" VALUES('windsor.george-v+teck.mary+family','windsor.edward-viii',0);
INSERT INTO "family_children" VALUES('saxe-coburg-gotha.albert+hanover.victoria+family','saxe-coburg-gotha.alice',2);
INSERT INTO "family_children" VALUES('hesse-darmstadt.ludwig-iv+saxe-coburg-gotha.alice+family','hesse-darmstadt.victoria',0);
INSERT INTO "family_children" VALUES('hesse-darmstadt.ludwig-ii+baden.wilhelmine+family','hesse-darmstadt.karl',1);
INSERT INTO "family_children" VALUES('hesse-darmstadt.karl+hohenzollern.elisabeth+family','hesse-darmstadt.ludwig-iv',0);
INSERT INTO "family_children" VALUES('glucksburg.christian-ix+hesse-kassel.louise+family','glucksburg.alexandra',1);
INSERT INTO "family_children" VALUES('glucksburg.christian-ix+hesse-kassel.louise+family','glucksburg.george-i',2);
INSERT INTO "family_children" VALUES('glucksburg.george-i+romanov.olga-constantinovna+family','glucksburg.andrew',6);
COMMIT;
