BEGIN TRANSACTION;
INSERT INTO "events" VALUES('hesse-darmstadt+founded',1740,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.ludwig-ix+birth',1719,12,15,'Darmstadt, Landgraviate of Hesse-Darmstadt',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.ludwig-ix+death',1790,4,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.ludwig-ix+hesse-darmstadt.landgrave+start',1768,10,12,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.friederike-luise+birth',1751,10,16,'Prenzlau, Electorate of Brandenburg',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.friederike-luise+death',1805,2,25,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.ludwig-i+birth',1753,6,14,'Prenzlau, Margraviate of Brandenburg',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.ludwig-i+death',1830,4,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.ludwig-i+hesse-and-by-rhine.grand-duke+start',1806,8,14,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.ludwig-i+hesse-darmstadt.landgrave+start',1790,4,6,NULL,NULL,NULL,NULL,'Ludwig X',NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.landgrave+abolished',1806,8,14,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('hesse-darmstadt.ludwig-ix+hesse-darmstadt.friederike-luise+family-1+married',1741,8,12,'Zweibrücken, Duchy of Palatinate-Zweibrücken',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.elizabeth-ii+birth',1926,4,21,'Mayfair, London, England',NULL,'York','of','Elizabeth',NULL,NULL);
INSERT INTO "events" VALUES('windsor.elizabeth-ii+death',2022,9,8,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.elizabeth-ii+united-kingdom.queen+start',1952,2,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('mountbatten.philip+birth',1921,6,10,'Mon Repos, Corfu, Greece',NULL,'Glücksburg','of','Philip',NULL,NULL);
INSERT INTO "events" VALUES('mountbatten.philip+death',2021,4,9,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('mountbatten.philip+edinburgh.duke+start',1947,11,20,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('mountbatten.philip+windsor.elizabeth-ii+family+marriage',1947,11,20,'Westminster Abbey, London, England',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES('windsor.charles-iii+birth',1948,11,14,'Buckingham Palace, London, England',NULL,'Edinburgh','of','Charles',NULL,NULL);
INSERT INTO "events" VALUES('windsor.charles-iii+united-kingdom.king+start',2022,9,8,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "houses" VALUES('hesse','Hesse',NULL,NULL,NULL,NULL);
INSERT INTO "houses" VALUES('hesse-darmstadt','Hesse-Darmstadt','hesse',NULL,'hesse-darmstadt.ludwig-ix','hesse-darmstadt+founded');
INSERT INTO "houses" VALUES('windsor','Windsor',NULL,NULL,NULL,NULL);
INSERT INTO "houses" VALUES('glucksburg','Glücksburg',NULL,NULL,NULL,NULL);
INSERT INTO "houses" VALUES('mountbatten','Mountbatten',NULL,'battenberg',NULL,NULL);
INSERT INTO "houses" VALUES('battenberg','Battenberg','hesse-darmstadt',NULL,NULL,NULL);
INSERT INTO "titles" VALUES('hesse-darmstadt.landgrave','Landgrave of Hesse-Darmstadt',NULL,NULL,'hesse-darmstadt.landgrave+abolished');
INSERT INTO "titles" VALUES('hesse-and-by-rhine.grand-duke','Grand Duke of Hesse and by Rhine',NULL,NULL,NULL);
INSERT INTO "titles" VALUES('united-kingdom.king','King of the United Kingdom','Monarch of the United Kingdom',NULL,NULL);
INSERT INTO "titles" VALUES('united-kingdom.queen','Queen of the United Kingdom','Monarch of the United Kingdom',NULL,NULL);
INSERT INTO "titles" VALUES('edinburgh.duke','Duke of Edinburgh',NULL,NULL,NULL);
INSERT INTO "people" VALUES('hesse-darmstadt.ludwig-ix','Ludwig',NULL,NULL,'Ludwig IX',NULL,NULL,'hesse-darmstadt.ludwig-ix+birth','hesse-darmstadt.ludwig-ix+death','hesse-darmstadt',NULL,'male');
INSERT INTO "people" VALUES('hesse-darmstadt.friederike-luise','Friederike Luise','Hesse-Darmstadt','of',NULL,NULL,NULL,'hesse-darmstadt.friederike-luise+birth','hesse-darmstadt.friederike-luise+death','hesse-darmstadt',NULL,'female');
INSERT INTO "people" VALUES('hesse-darmstadt.ludwig-i','Ludwig',NULL,NULL,'Ludwig I',NULL,NULL,'hesse-darmstadt.ludwig-i+birth','hesse-darmstadt.ludwig-i+death','hesse-darmstadt',NULL,'male');
INSERT INTO "people" VALUES('windsor.elizabeth-ii','Elizabeth Alexandra Mary',NULL,NULL,'Elizabeth II',NULL,NULL,'windsor.elizabeth-ii+birth','windsor.elizabeth-ii+death','windsor',NULL,'female');
INSERT INTO "people" VALUES('mountbatten.philip','Philip','Mountbatten',NULL,NULL,NULL,NULL,'mountbatten.philip+birth','mountbatten.philip+death','mountbatten','glucksburg','male');
INSERT INTO "people" VALUES('windsor.charles-iii','Charles Philip Arthur George',NULL,NULL,'Charles III',NULL,NULL,'windsor.charles-iii+birth',NULL,'windsor',NULL,'male');
INSERT INTO "tenures" VALUES(1,'hesse-darmstadt.ludwig-ix','hesse-darmstadt.landgrave','hesse-darmstadt.ludwig-ix+hesse-darmstadt.landgrave+start',NULL,NULL,0,NULL);
INSERT INTO "tenures" VALUES(2,'hesse-darmstadt.ludwig-i','hesse-and-by-rhine.grand-duke','hesse-darmstadt.ludwig-i+hesse-and-by-rhine.grand-duke+start',NULL,NULL,0,NULL);
INSERT INTO "tenures" VALUES(3,'hesse-darmstadt.ludwig-i','hesse-darmstadt.landgrave','hesse-darmstadt.ludwig-i+hesse-darmstadt.landgrave+start',NULL,NULL,0,NULL);
INSERT INTO "tenures" VALUES(4,'windsor.elizabeth-ii','united-kingdom.queen','windsor.elizabeth-ii+united-kingdom.queen+start',NULL,NULL,0,NULL);
INSERT INTO "tenures" VALUES(5,'mountbatten.philip','edinburgh.duke','mountbatten.philip+edinburgh.duke+start',NULL,NULL,0,NULL);
INSERT INTO "tenures" VALUES(6,'windsor.charles-iii','united-kingdom.king','windsor.charles-iii+united-kingdom.king+start',NULL,NULL,0,NULL);
INSERT INTO "families" VALUES('hesse-darmstadt.ludwig-ix+hesse-darmstadt.friederike-luise+family-1','hesse-darmstadt.ludwig-ix','hesse-darmstadt.friederike-luise','hesse-darmstadt.ludwig-ix+hesse-darmstadt.friederike-luise+family-1+married',NULL);
INSERT INTO "families" VALUES('mountbatten.philip+windsor.elizabeth-ii+family','mountbatten.philip','windsor.elizabeth-ii','mountbatten.philip+windsor.elizabeth-ii+family+marriage',NULL);
INSERT INTO "family_children" VALUES('hesse-darmstadt.ludwig-ix+hesse-darmstadt.friederike-luise+family-1','hesse-darmstadt.ludwig-i',0);
INSERT INTO "family_children" VALUES('mountbatten.philip+windsor.elizabeth-ii+family','windsor.charles-iii',0);
COMMIT;
