BEGIN TRANSACTION;
INSERT INTO "events" VALUES(1,1740,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES(2,1719,12,15,'Darmstadt, Landgraviate of Hesse-Darmstadt',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES(3,1790,4,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES(4,1768,10,12,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES(5,1751,10,16,'Prenzlau, Electorate of Brandenburg',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES(6,1805,2,25,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES(7,1753,6,14,'Prenzlau, Margraviate of Brandenburg',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES(8,1830,4,6,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES(9,1806,8,14,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES(10,1790,4,6,NULL,NULL,NULL,NULL,'Ludwig X',NULL,NULL);
INSERT INTO "events" VALUES(11,1806,8,14,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "events" VALUES(12,1741,8,12,'Zweibrücken, Duchy of Palatinate-Zweibrücken',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "houses" VALUES('hesse','Hesse',NULL,NULL,NULL,NULL);
INSERT INTO "houses" VALUES('hesse-darmstadt','Hesse-Darmstadt','hesse','hesse-darmstadt.ludwig-ix',1,NULL);
INSERT INTO "titles" VALUES('hesse-darmstadt.landgrave','Landgrave of Hesse-Darmstadt',NULL);
INSERT INTO "titles" VALUES('hesse-and-by-rhine.grand-duke','Grand Duke of Hesse and by Rhine',NULL);
INSERT INTO "people" VALUES('hesse-darmstadt.ludwig-ix','Ludwig',NULL,NULL,'Ludwig IX',NULL,NULL,2,3,'hesse-darmstadt','male');
INSERT INTO "people" VALUES('hesse-darmstadt.friederike-luise','Friederike Luise','Hesse-Darmstadt','of',NULL,NULL,NULL,5,6,'hesse-darmstadt','female');
INSERT INTO "people" VALUES('hesse-darmstadt.ludwig-i','Ludwig',NULL,NULL,'Ludwig I',NULL,NULL,7,8,'hesse-darmstadt','male');
INSERT INTO "tenures" VALUES(1,'hesse-darmstadt.ludwig-ix','hesse-darmstadt.landgrave',4,NULL,NULL,0,NULL);
INSERT INTO "tenures" VALUES(2,'hesse-darmstadt.ludwig-i','hesse-and-by-rhine.grand-duke',9,NULL,NULL,0,NULL);
INSERT INTO "tenures" VALUES(3,'hesse-darmstadt.ludwig-i','hesse-darmstadt.landgrave',10,11,NULL,0,NULL);
INSERT INTO "families" VALUES('hesse-darmstadt.ludwig-ix+hesse-darmstadt.friederike-luise+family-1','hesse-darmstadt.ludwig-ix','hesse-darmstadt.friederike-luise',12,NULL);
INSERT INTO "family_children" VALUES('hesse-darmstadt.ludwig-ix+hesse-darmstadt.friederike-luise+family-1','hesse-darmstadt.ludwig-i',0);
COMMIT;
